fix(header): `search` should be always visible in PC UI
Magickbase/ckb-explorer-frontend pull request #155
Opened 2023-11-15 19:30 UTC by Daryl-L

https://github.com/Magickbase/ckb-explorer-public-issues/issues/472
https://github.com/Magickbase/ckb-explorer-public-issues/issues/473

2023-11-17 08:52 UTC, Keith-CY approved these changes

2023-11-20 07:23 UTC, WhiteMinds commented
The layout logic has changed, which is likely unexpected.

New:

![image](https://github.com/Magickbase/ckb-explorer-frontend/assets/9160743/2fa2ea0b-bfef-4f45-89c0-91ebbd519d1a)

Original:

![image](https://github.com/Magickbase/ckb-explorer-frontend/assets/9160743/beaf134f-03a6-4f98-b5f3-dbd4e1ca889f)

2023-11-20 07:49 UTC, WhiteMinds requested changes

2023-11-20 07:49 UTC, WhiteMinds commented on src/utils/hook.ts
> +export const useIsMobile = (max?: number) => useMediaQuery(`(max-width: ${max ?? MOBILE_DEVICE_MAX_WIDTH}px)`)
`useIsMobile` is actually a JavaScript version of the 750px breakpoint. It should be a fixed value that is equal to the breakpoint defined in CSS, so it should not accept a variable parameter.

2023-12-08 06:36 UTC, Daryl-L commented
> The layout logic has changed, which is likely unexpected.
> 
> New:
> 
> ![image](https://private-user-images.githubusercontent.com/9160743/284168943-2fa2ea0b-bfef-4f45-89c0-91ebbd519d1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMTc2MTksIm5iZiI6MTcwMjAxNzMxOSwicGF0aCI6Ii85MTYwNzQzLzI4NDE2ODk0My0yZmEyZWEwYi1iZmVmLTRmNDUtODljMC05MWViYmQ1MTlkMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDhUMDYzNTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjllMjUwMDg1ZWYxZmNhMDk3MzMwOGIyN2NkNzFmYjI3NGQ3ZWY2Nzc5NWVlZTFhNjA0MjA0MGRhMTBjNGM2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c5D7awBwb9WKkyW3G3my_2DHlMIQWUzzREDrP7rkbmY)
> 
> Original:
> 
> ![image](https://private-user-images.githubusercontent.com/9160743/284169110-beaf134f-03a6-4f98-b5f3-dbd4e1ca889f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMTc2MTksIm5iZiI6MTcwMjAxNzMxOSwicGF0aCI6Ii85MTYwNzQzLzI4NDE2OTExMC1iZWFmMTM0Zi0wM2E2LTRmOTgtYjVmMy1kYmQ0ZTFjYTg4OWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDhUMDYzNTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjgzNTg3Njg2ZjBmNTA2MTExM2NjNzhhMmUxMDkxZmJhZjQyZDJlOWExNGJiYTY3YzE1MDQxZjRiYmRiY2NjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BTjIYqbypjmjhTjzXI86Pg-u03FboqBxGA7VjY0-6yw)

![Uploading image.png…]()
This is the reason here, but why? I didn't find it in the design draft

2023-12-08 07:03 UTC, Keith-CY commented
> The layout logic has changed, which is likely unexpected.
> 
> New:
> 
> image
> 
> Original:
> 
> image
> 
> Uploading image.png…
> This is the reason here, but why? I didn't find it in the design draft

Images are broken

2023-12-08 07:10 UTC, Daryl-L commented
https://github.com/Magickbase/ckb-explorer-frontend/blob/db52e40231355f2b8e6db8fb109b0e6a306855de/src/index.css#L46

2023-12-12 05:43 UTC, Keith-CY commented
> https://github.com/Magickbase/ckb-explorer-frontend/blob/db52e40231355f2b8e6db8fb109b0e6a306855de/src/index.css#L46

Which comment is this replied to

2023-12-14 08:00 UTC, WhiteMinds approved these changes

2023-12-19 10:57 UTC, Keith-CY commented
Conflicted

2023-12-27 03:23 UTC, Keith-CY commented
![output](https://github.com/Magickbase/ckb-explorer-frontend/assets/7271329/9c9c8d5a-6e80-48a2-8841-246d7f0ddf7a)

Notice the layout at 0:22 and 0:33
0:22, items in the header are connected to each other
0:33, search field in the dropdown is connected to the border, but a span is added when the width is smaller

2023-12-27 06:48 UTC, FrederLu commented
The search box switching is weird.
Whether to switch to the top only when the lower search box is completely blocked, or to hide the top search box when the search box is about to appear on the page.

https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/9a8044f4-a190-4cc7-973f-3facd670a0f3

2024-01-02 04:16 UTC, Daryl-L commented
> ![output](https://private-user-images.githubusercontent.com/7271329/292950478-9c9c8d5a-6e80-48a2-8841-246d7f0ddf7a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjkwNDksIm5iZiI6MTcwNDE2ODc0OSwicGF0aCI6Ii83MjcxMzI5LzI5Mjk1MDQ3OC05YzljOGQ1YS02ZTgwLTQ4YTItODg0MS0yNDZkN2YwZGRmN2EuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMDQxMjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDRhOWVlNmFhZTBhMjQxMjdkYmU0MzA4NWQwNDVhNmRlZTUxNjJjY2JlOTMxMzYwZWRmZTFmYzQ2MzI1ZDgzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ax_Ua2icjyBmX2f-fyIYD3XEoNPtD5bhU3TM8kNwTFA) [ ![output](https://private-user-images.githubusercontent.com/7271329/292950478-9c9c8d5a-6e80-48a2-8841-246d7f0ddf7a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjkwNDksIm5iZiI6MTcwNDE2ODc0OSwicGF0aCI6Ii83MjcxMzI5LzI5Mjk1MDQ3OC05YzljOGQ1YS02ZTgwLTQ4YTItODg0MS0yNDZkN2YwZGRmN2EuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMDQxMjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDRhOWVlNmFhZTBhMjQxMjdkYmU0MzA4NWQwNDVhNmRlZTUxNjJjY2JlOTMxMzYwZWRmZTFmYzQ2MzI1ZDgzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ax_Ua2icjyBmX2f-fyIYD3XEoNPtD5bhU3TM8kNwTFA) ](https://private-user-images.githubusercontent.com/7271329/292950478-9c9c8d5a-6e80-48a2-8841-246d7f0ddf7a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjkwNDksIm5iZiI6MTcwNDE2ODc0OSwicGF0aCI6Ii83MjcxMzI5LzI5Mjk1MDQ3OC05YzljOGQ1YS02ZTgwLTQ4YTItODg0MS0yNDZkN2YwZGRmN2EuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMDQxMjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDRhOWVlNmFhZTBhMjQxMjdkYmU0MzA4NWQwNDVhNmRlZTUxNjJjY2JlOTMxMzYwZWRmZTFmYzQ2MzI1ZDgzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ax_Ua2icjyBmX2f-fyIYD3XEoNPtD5bhU3TM8kNwTFA) [ ](https://private-user-images.githubusercontent.com/7271329/292950478-9c9c8d5a-6e80-48a2-8841-246d7f0ddf7a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjkwNDksIm5iZiI6MTcwNDE2ODc0OSwicGF0aCI6Ii83MjcxMzI5LzI5Mjk1MDQ3OC05YzljOGQ1YS02ZTgwLTQ4YTItODg0MS0yNDZkN2YwZGRmN2EuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMDQxMjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDRhOWVlNmFhZTBhMjQxMjdkYmU0MzA4NWQwNDVhNmRlZTUxNjJjY2JlOTMxMzYwZWRmZTFmYzQ2MzI1ZDgzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ax_Ua2icjyBmX2f-fyIYD3XEoNPtD5bhU3TM8kNwTFA)
> 
> Notice the layout at 0:22 and 0:33 0:22, items in the header are connected to each other 0:33, search field in the dropdown is connected to the border, but a span is added when the width is smaller

for 0:22, different from the design draft.
1. there is an extra item in the search component, but not found in desgin draft.
2. I found that the size between 1024px and 1920px is not listed in the design draft, so I just make them to auto adjust

2024-01-03 02:54 UTC, FrederLu commented
<img width="1025" alt="image" src="https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/3906939c-3584-45fc-96e0-10e46f20485b">
<img width="1028" alt="image" src="https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/2ee1f780-e228-4b34-9d79-d1a22e7b543c">

1. Changing the resolution will also cause copywriting overlap.
2. At `1024px * 764px`, the search box will suddenly change size, but the default information in the search is gone, and the cursor will not appear when clicking the search box.
3. In Screenshot 2, it is found that the width of the top bar has changed.


---
2、The search box size on the mobile phone is abnormal.
<img width="313" alt="image" src="https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/7bae8437-0e9d-4261-8238-1dbfde57a360"><img width="339" alt="image" src="https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/42eb3c6e-7ec7-4724-a661-2fb7ce4eb5c4">

2024-01-03 04:16 UTC, FrederLu commented
<img width="673" alt="image" src="https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/074eb6e3-b01c-4a57-a7a5-55f74a9700f8">
This problem still exists.

2024-01-08 03:42 UTC, FrederLu approved these changes

2024-01-08 18:21 UTC, merged